plugins: 
- jekyll-include-cache

title: LMC
logo: /assets/img/WhiteText.png
description: A simple app for people who like simple things.
show_downloads: false
minimal_mistakes_skin: dark

atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true # true, false (default)

footer:
  links:
     - label: "GitLab"
       icon: "fab fa-fw fa-gitlab"
       url: "https://code.cs.umanitoba.ca/3350-winter-2021-a03/listmycourses-comp3350-a03-group11"

 
remote_theme: mmistakes/minimal-mistakes@4.22.0

