plugins: 
- jekyll-include-cache

title: List My Courses
logo: /assets/img/BlackText.png
description: A simple app for people who like simple things.
show_downloads: false
theme: minimal-mistakes-jekyll
